server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. RUTA DE RUTINAS (Con RewritePath para limpiar la URL interna)
        - id: rutina-service
          uri: http://rutina-service:8086
          predicates:
            - Path=/api/rutinas/**
          filters:
            - RewritePath=/api/rutinas/(?<segment>.*), /$\{segment}

        # 2. RUTA DE SOCIOS
        - id: socios-service
          uri: http://socios-service:8082
          predicates:
            - Path=/api/socios/**
          filters:
            - RewritePath=/api/socios/(?<segment>.*), /$\{segment}

        # 3. RUTA DE EMPLEADOS
        - id: empleados-service
          uri: http://empleados-service:8081
          predicates:
            - Path=/api/empleados/**
          filters:
            - RewritePath=/api/empleados/(?<segment>.*), /$\{segment}

        # 4. OTRAS RUTAS (Facturacion, Inventario, Comercial)
        - id: facturacion-service
          uri: http://facturacion-service:8084
          predicates:
            - Path=/api/facturacion/**
        - id: comercial-service
          uri: http://comercial-service:8083
          predicates:
            - Path=/api/comercial/**
        - id: inventario-service
          uri: http://inventario-service:8085
          predicates:
            - Path=/api/inventario/**

eureka:
  client:
    enabled: false


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Rutinas
        url: /api/rutinas/v3/api-docs
      - name: Socios
        url: /api/socios/v3/api-docs
      - name: Empleados
        url: /api/empleados/v3/api-docs