server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: facturacion-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/facturacion/**
        - id: socios-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/socios/**
        - id: comercial-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/comercial/**
        - id: empleados-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/empleados/**
        - id: inventario-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/inventario/**
        - id: rutina-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/rutinas/**

eureka:
  client:
    enabled: false