
CREATE DATABASE IF NOT EXISTS comercial_db;
CREATE DATABASE IF NOT EXISTS facturacion_db;
CREATE DATABASE IF NOT EXISTS empleados_db;
CREATE DATABASE IF NOT EXISTS inventario_db;
CREATE DATABASE IF NOT EXISTS rutina_db;
CREATE DATABASE IF NOT EXISTS socios_db;