server:
  port: 8083

spring:
  application:
    name: comercial-service

  datasource:
    url: jdbc:mysql://mysql:3306/comercial_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: jdbc:mysql://mysql:3306/comercial_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    user: root
    password: 123456
    locations: classpath:db/migration

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

facturacion:
  service:
    url: http://facturacion-service:8084
