server.port=8084
spring.application.name=facturacion-service


# CAMBIO: Se cambia 'localhost' por 'mysql' y se agrega '?createDatabaseIfNotExist=true'
spring.datasource.url=jdbc:mysql://mysql:3306/facturacion_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://mysql:3306/facturacion_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.flyway.user=root
spring.flyway.password=123456
spring.flyway.locations=classpath:db/migration

# Eureka desactivado
eureka.client.enabled=false